### ISSUE TITLE
HTTP inflight request is aborted ignoring preWait

### ISSUE THREAD

**Issue by mivanilov** [arrow-kt/suspendapp#116]
**Issue**: http inflight request is aborted on app getting e.g. SIGTERM even though SuspendApp `preWait` is configured to be e.g. 10s.  

**Expectation**: http inflight requests are allowed to complete within `preWait` on app getting e.g. SIGTERM.  

**Steps to reproduce**:  (example app code [issue-suspendapp-inflight-abort.zip](https://github.com/arrow-kt/suspendapp/files/14196958/issue-suspendapp-inflight-abort.zip))
- Start app with `-Dio.ktor.server.engine.ShutdownHook=false`
- curl http://localhost/ping -v
- kill -s SIGTERM \`lsof -t -i:80\`
- Inflight request is aborted immediately ignoring `preWait`

Looks like an issue is with Ktor itself as I also get the same outcome using just Ktor `embeddedServer` ([also raised an issue with Ktor](https://youtrack.jetbrains.com/issue/KTOR-6755/HTTP-inflight-request-is-aborted-ignoring-shutdownGracePeriod))
Nevertheless I thought maybe Arrow community could also help investigating this issue.

**Comment by nomisRev** [comment]
@mivanilov thank you for creating this ticket! It'll allow me to keep an eye on things.

**Comment by mivanilov** [comment]
@nomisRev no actual issue here, my bad, sorry for this... I've explained it here https://youtrack.jetbrains.com/issue/KTOR-6755/HTTP-inflight-request-is-aborted-ignoring-shutdownGracePeriod#focus=Comments-27-9188264.0-0  
Closing this ticket too.
